version: '3.8'

services:
  app:
    image: missionimpossible
    container_name: mission_app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    networks:
      - app-network

networks:
  app-network:
    driver: bridge