name: Mars Mission CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DOCKER_HUB_REPO: pelagiavlas
  BACKEND_IMAGE: missionimpossible-backend
  FRONTEND_IMAGE: missionimpossible-frontend

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install pytest pylint

      - name: Lint Python Code
        run: |
          pylint --fail-under=7.0 backend/

      - name: Run Unit Tests
        run: |
          pytest backend/tests/ --cov=backend --cov-report=xml

  docker-build-push:
    runs-on: ubuntu-latest
    needs: test-and-lint
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push Backend
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: |
            ${{ env.DOCKER_HUB_REPO }}/${{ env.BACKEND_IMAGE }}:latest
            ${{ env.DOCKER_HUB_REPO }}/${{ env.BACKEND_IMAGE }}:${{ github.sha }}

      - name: Build and Push Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ env.DOCKER_HUB_REPO }}/${{ env.FRONTEND_IMAGE }}:latest
            ${{ env.DOCKER_HUB_REPO }}/${{ env.FRONTEND_IMAGE }}:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: docker-build-push
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy with Docker Compose
        run: |
          docker-compose -f docker-compose.prod.yml up -d